export type NotificationEvent =
  | 'payment.confirmed'
  | 'purchase.created'
  | 'subscription.expiring'
  | 'usage.limit-reached'
  | 'monitoring.down'
  | 'monitoring.up'
  | 'monitoring.unstable'
  | 'custom.manual'
  | 'user.bark-connected'
  | 'addon.canceled'
  | 'plan.changed'
